### ISSUE TITLE
登入後成立訂單時會造成 heroku error

### ISSUE THREAD

**Issue by ArcherHuang** [ArcherHuang/e-commerce#289]
* 步驟
   * 使用者登入成功
   * 點選購物車
   * 點選「建立訂單，前往結帳」按鈕
   * 出現「Application error」
* 畫面
   ![](https://oranwind.s3.amazonaws.com/2019/Nov/_____2019_11_14___5_50_36-1573681892734.png)
   ![](https://oranwind.s3.amazonaws.com/2019/Nov/_____2019_11_14___5_50_51-1573681928796.png)

**Comment by jacs0110** [comment]
@ArcherHuang 我這裡暫時無法重現，晚一點再研究看看

**Comment by ArcherHuang** [comment]
在 local 端可以正常運作，但在 heroku 會有問題
